[package]
name = "esp-nimble-host"
version = "0.1.0"
edition = "2024"
authors = ["Peeriot GmbH <info@peeriot.io>"]
publish = false

[features]
esp32c6 = ["esp-radio/esp32c6"]

[dependencies]
esp-radio = { git = "ssh://git@github.com/peeriot/esp-hal.git", branch = "feature/ble-host-npl-upstream", features = [
  "ble-host-npl",
  "log-04",
  "unstable",
] }
esp-hal = { git = "ssh://git@github.com/peeriot/esp-hal.git", branch = "feature/ble-host-npl-upstream", features = [
  "unstable",
] }
embassy-sync = "0.7.2"
embassy-futures = "0.1.2"
log = "0.4.29"
tinyrlibc = { version = "0.5.1", default-features = false, features = [
  "strcat",
  "strcpy",
  "strlen",
] }
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
portable-atomic = "1.13.0"
static_cell = "2.1.1"
thiserror = { version = "2.0.18", default-features = false }
uuid = { version = "1.20.0", default-features = false }
num_enum = { version = "0.7.5", default-features = false }
bytes = { version = "1.11.1", default-features = false }
heapless = "0.9.2"

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.51"
walkdir = "2.5.0"
ureq = "3"
flate2 = "1"
tar = "0.4"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
